import type { BoardSwimlane } from '../types/board';

export type CardPaletteId = 'classic' | 'docme360' | 'pastel';

export type CardPalette = {
  id: CardPaletteId;
  name: string;
  description: string;
  /** Hand-tuned colors for the first lanes, most-distinct-first. */
  curated: string[];
  /** Overflow generator character (golden-angle HSL) for lane N+1 onward. */
  overflow: { saturation: number; lightness: number };
};

/**
 * All palettes are light-to-mid backgrounds so the dark card text stays
 * readable in every theme (cards carry their own background even in dark
 * mode). Beyond the curated list, colors are generated by rotating the hue
 * by the golden angle — successive hues land far apart, so any number of
 * lanes stays as distinct as possible without overlap.
 */
export const CARD_PALETTES: CardPalette[] = [
  {
    id: 'classic',
    name: 'Classic vivid',
    description:
      'The bright per-person palette boards ship with. Uses each lane’s own stored color.',
    curated: [
      '#4ade80', '#2dd4bf', '#a78bfa', '#f87171', '#fcd34d', '#a3e635',
      '#fb923c', '#38bdf8', '#f9a8d4', '#818cf8', '#e879f9',
    ],
    overflow: { saturation: 78, lightness: 72 },
  },
  {
    id: 'docme360',
    name: 'DocMe360',
    description:
      'Corporate and calm — sky blue, brick, and lavender from the brand, with muted cool tones.',
    curated: [
      '#96c2e9', // sky — brand
      '#e3a4a4', // brick tint — brand red
      '#a892c9', // lavender — from docme360.com
      '#8fc9b2', // seafoam
      '#ddc58f', // sand
      '#7fa3cb', // steel blue
      '#d6a6c9', // mauve
      '#aecb92', // moss
      '#d9b28f', // clay
      '#8ed1da', // ice
      '#b3aade', // periwinkle
    ],
    overflow: { saturation: 34, lightness: 70 },
  },
  {
    id: 'pastel',
    name: 'Soft pastel',
    description: 'Gentle washed-out tints — easy on the eyes at a glance.',
    curated: [
      '#c8ecd2', '#b8e6dc', '#d4c8f0', '#f5c2c2', '#f7e3a8', '#dcefb5',
      '#f7d2b0', '#c2e2f5', '#f7c8dd', '#ccd2f7', '#f0ccf5',
    ],
    overflow: { saturation: 60, lightness: 84 },
  },
];

/** Golden angle in degrees — consecutive hues land maximally apart. */
const GOLDEN_ANGLE = 137.508;

function overflowColor(palette: CardPalette, index: number): string {
  // Continue the rotation past the curated list; offset the start so the
  // first generated hue doesn't sit near curated hue 0.
  const hue = (60 + index * GOLDEN_ANGLE) % 360;
  const { saturation, lightness } = palette.overflow;
  // Alternate lightness slightly so near-hue collisions (after many turns)
  // still differ in tone.
  const l = lightness + (index % 2 === 0 ? 0 : -7);
  return `hsl(${hue.toFixed(1)}, ${saturation}%, ${l}%)`;
}

export function paletteColor(palette: CardPalette, index: number): string {
  return index < palette.curated.length
    ? palette.curated[index]!
    : overflowColor(palette, index - palette.curated.length);
}

/**
 * Display color for every lane on a board under the chosen palette.
 * 'classic' respects each lane's stored color (custom templates keep their
 * hand-picked colors); other palettes assign by lane order, so the mapping
 * is stable for a given board.
 */
export function laneColorMap(
  swimlanes: BoardSwimlane[],
  paletteId: CardPaletteId,
): Record<string, string> {
  const palette =
    CARD_PALETTES.find((p) => p.id === paletteId) ?? CARD_PALETTES[0]!;
  const map: Record<string, string> = {};
  swimlanes.forEach((lane, index) => {
    map[lane.id] =
      paletteId === 'classic'
        ? lane.color || paletteColor(palette, index)
        : paletteColor(palette, index);
  });
  return map;
}
